spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bill-manager?serverTimezone=GMT
    username: root
    password: 111111
  application:
    name: Bill-Service
server:
  port: 8002
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.aliang.mapper
# Eureka配置
eureka:
  client:
    register-with-eureka: true # 表示是否将自己注册进Eureka 默认为true
    fetch-registry: true # 表示是否从EurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
    # register-with-eureka和fetch-registry 默认是true,所以不用设置
  instance:
    prefer-ip-address: true # 优先使用ip地址