server:
  port: 80 # 设置端口
spring:
  application:
    name: gateway-server # 设置服务名称
  cloud:
    gateway:
      routes:
        - id: bill-service-gateway  # 路由服务的id，随便起
          uri: lb://Bill-Consumer # 使用服务名称,符合断言的请求会被转发到这个服务上,lb表示LoadBalancerClient的意思，gateway会将后面的User-Service通过Eureka解析为实际的主机和端口，并进行Ribbon负载均衡处理。
          predicates: # 指定断言的规则，即配置映射路径
            - Path=/consumer/**  # 断言的规则，
            # 如果请求地址为 http://127.0.0.1:10010/consumer/queryById/1 ，则符合断言规则，这个请求就会被转发到uri指定的服务地址 http://127.0.0.1:8001/consumer/queryById/1
          filters:
            - StripPrefix=1 # 此处指定去除前缀的段数
            - PrefixPath=/bill/consumer #添加请求路径的前缀
        - id: bill-pages-gateway
          uri: lb://Bill-Consumer
          predicates:
            - Path=/**
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka #指定eureka地址
  instance:
    prefer-ip-address: true  # 优先使用ip地址